import Anthropic from "@anthropic-ai/sdk";
import { ANTHROPIC_PRICING } from "../types";
import type { DetectedPlatform, SupabaseService } from "../types";
import { isSafeRelativePath } from "../utils/paths";

let client: Anthropic | null = null;

function getClient(): Anthropic {
  if (!client) {
    client = new Anthropic({
      apiKey: process.env.ANTHROPIC_API_KEY,
      maxRetries: 5,
    });
  }
  return client;
}

type ModelId = keyof typeof ANTHROPIC_PRICING;
export const MODEL: ModelId = (process.env.AI_MODEL as ModelId) || "claude-opus-4-7";

export interface AIResponse {
  content: string;
  inputTokens: number;
  outputTokens: number;
}

export interface AnalysisContext {
  platform: DetectedPlatform;
  targetServices: SupabaseService[];
  platformFiles: string[];
  platformPatterns: string[];
  modelOverride?: string;
}

/** Only allow models we have pricing for; ignore arbitrary client-supplied strings. */
export function resolveModel(override?: string): ModelId {
  if (override && override in ANTHROPIC_PRICING) {
    return override as ModelId;
  }
  return MODEL;
}

export async function analyzeFile(
  filePath: string,
  content: string,
  ctx: AnalysisContext,
): Promise<AIResponse & { needsMigration: boolean; reason: string }> {
  const anthropic = getClient();
  const model = resolveModel(ctx.modelOverride);

  const response = await anthropic.messages.create({
    model,
    max_tokens: 500,
    messages: [
      {
        role: "user",
        content: `You are analyzing a codebase built on "${ctx.platform}" that is being migrated to run as a standalone app with Supabase as the backend. Your job is to flag files that need ANY changes. Be aggressive — when in doubt, flag the file. It is much better to flag a file that turns out to not need changes than to miss one that does.

## Flag the file (needs_migration: true) if it has ANY of these:
- Imports or references the platform SDK or packages (e.g. @lovable.dev/*, @base44/*, @replit/*, @bolt/*, lovable-tagger, etc.)
- Imports from ANY file listed in the "platform files" section below, even indirectly
- Imports from platform-generated directories (e.g. @/integrations/lovable/*, @/integrations/supabase/*)
- Uses non-standard environment variable names (e.g. VITE_SUPABASE_PUBLISHABLE_KEY instead of VITE_SUPABASE_ANON_KEY)
- Contains auto-generated comments (e.g. "auto-generated by Lovable", "Do not edit it directly")
- Has platform-specific dependencies or devDependencies in package.json
- Contains platform-specific plugin config (e.g. lovable-tagger in vite.config)
- Contains platform URLs or branding (e.g. lovable.dev, base44.app, @Lovable in meta tags)
- Is a config file (.env, index.html, README) that references the platform in any way
- Uses platform auth wrappers instead of direct supabase.auth calls

## ONLY skip the file if it is completely clean:
- Pure UI component (buttons, cards, layouts) with zero platform references
- Standard library usage only (React, Radix, Tailwind, date-fns, etc.)
- No imports from any platform-flagged file or integration directory

When in doubt, flag it. False positives are acceptable; false negatives are not.

## Files already identified as containing platform-specific code
${ctx.platformFiles.map((f) => `- ${f}`).join("\n")}

## Platform patterns found in the codebase
${ctx.platformPatterns.map((p) => `- ${p}`).join("\n")}

## Supabase services used in this project
${ctx.targetServices.join(", ")}

## File to analyze
File: ${filePath}

\`\`\`
${content.substring(0, 8000)}
\`\`\`

Respond in this exact JSON format (no markdown fences):
{"needs_migration": true/false, "reason": "brief explanation of what specifically needs to change, or why it can be skipped"}`,
      },
    ],
  });

  const text =
    response.content[0].type === "text" ? response.content[0].text : "{}";
  let parsed: { needs_migration: boolean; reason: string };
  try {
    parsed = JSON.parse(text);
  } catch {
    console.warn(`[ai] Failed to parse analysis response for ${filePath}: ${text.slice(0, 200)}`);
    parsed = { needs_migration: false, reason: "Could not parse analysis" };
  }

  return {
    content: text,
    inputTokens: response.usage.input_tokens,
    outputTokens: response.usage.output_tokens,
    needsMigration: parsed.needs_migration ?? false,
    reason: parsed.reason ?? "",
  };
}

function stripMarkdownFences(text: string): string {
  let result = text.trim();
  // Remove wrapping ```lang ... ``` if the entire response is fenced
  const fullFence = result.match(/^```[\w]*\n([\s\S]*?)\n```\s*$/);
  if (fullFence) return fullFence[1].trim();
  // Remove leading ``` line and trailing ``` line
  if (result.startsWith("```")) {
    result = result.replace(/^```[\w]*\n?/, "");
  }
  if (result.endsWith("```")) {
    result = result.replace(/\n?```\s*$/, "");
  }
  return result.trim();
}

export async function migrateFile(
  filePath: string,
  content: string,
  platform: DetectedPlatform,
  supabaseUrl: string,
  targetServices: SupabaseService[],
): Promise<AIResponse> {
  const anthropic = getClient();

  const response = await anthropic.messages.create({
    model: MODEL,
    max_tokens: 8000,
    system: "You are a code migration tool. You output ONLY raw source code. Never wrap output in markdown code fences (```). Never add explanatory comments, disclaimers, or notes about what you changed. Never output partial files or placeholders like '// rest of file unchanged'. Always output the complete file from first line to last.",
    messages: [
      {
        role: "user",
        content: `Migrate this file from ${platform} to use Supabase services.

File: ${filePath}
Supabase project URL: ${supabaseUrl}
Target services: ${targetServices.join(", ")}

Rules:
- Replace ALL proprietary ${platform} SDK imports/calls with @supabase/supabase-js equivalents
- Use createClient from @supabase/supabase-js for initialization
- Read SUPABASE_URL and SUPABASE_ANON_KEY from environment variables (VITE_ prefix for client-side)
- For database: use supabase.from('table').select/insert/update/delete
- For auth: use supabase.auth.signInWithPassword, signUp, getSession, etc.
- For storage: use supabase.storage.from('bucket').upload/download
- For realtime: use supabase.channel().on('postgres_changes', ...)
- Preserve the file's overall structure and non-platform-specific logic
- Output the COMPLETE migrated file, every line, no omissions

CRITICAL: Output raw source code only. No markdown fences. No \`\`\` markers. No explanations before or after the code.

Original file:
---START OF FILE---
${content}
---END OF FILE---

Migrated file:`,
      },
    ],
  });

  const text =
    response.content[0].type === "text" ? response.content[0].text : content;
  let migrated = stripMarkdownFences(text);

  return {
    content: migrated.trim(),
    inputTokens: response.usage.input_tokens,
    outputTokens: response.usage.output_tokens,
  };
}

export interface BuildFixResult {
  fixes: Map<string, string>;
  inputTokens: number;
  outputTokens: number;
}

export async function fixBuildErrors(
  buildLog: string,
  files: Map<string, string>,
  platform: string,
): Promise<BuildFixResult> {
  const anthropic = getClient();

  // Bound per-file and total size sent to the model to prevent unbounded
  // token usage from large/malicious files.
  const MAX_PER_FILE = 24_000;
  const MAX_TOTAL = 120_000;
  let budget = MAX_TOTAL;
  const fileList = Array.from(files.entries())
    .map(([path, content]) => {
      if (budget <= 0) return "";
      const slice = content.slice(0, Math.min(MAX_PER_FILE, budget));
      budget -= slice.length;
      return `### ${path}\n\`\`\`\n${slice}\n\`\`\``;
    })
    .filter(Boolean)
    .join("\n\n");

  const response = await anthropic.messages.create({
    model: MODEL,
    max_tokens: 16000,
    system: "You are a code repair tool. You output JSON containing complete corrected source files. Every file value must be the FULL file content from first line to last — never partial content, never placeholders, never comments explaining what to do instead of actual code. If you do not have enough context to fix a file, output it unchanged rather than adding explanatory comments.",
    messages: [
      {
        role: "user",
        content: `Fix build errors in a project migrated from ${platform} to Supabase.

## Build Error Log
---START OF LOG---
${buildLog.slice(-6000)}
---END OF LOG---

## Source Files
${fileList}

## Instructions
Analyze the build errors and fix the source files. Common issues:
- Missing imports or incorrect import paths
- Type errors from incorrect Supabase client usage
- Missing dependencies in package.json
- Incorrect environment variable names
- Syntax errors from migration

CRITICAL RULES:
- Every file in your response must contain the COMPLETE corrected file, every single line.
- Never output partial files, "// ... rest unchanged", or placeholder comments.
- Never output explanatory comments like "// NOTE: This file could not be fully reconstructed".
- If you cannot fully fix a file, return it unchanged rather than adding commentary.

Respond in this exact JSON format (no markdown fences around the JSON):
{"fixes": {"path/to/file.ts": "complete corrected file content here"}}

Only include files that need changes.`,
      },
    ],
  });

  const text = response.content[0].type === "text" ? response.content[0].text : "{}";
  let parsed: { fixes?: Record<string, string> };
  try {
    const cleaned = text.replace(/```json\n?/g, "").replace(/```\n?/g, "");
    parsed = JSON.parse(cleaned);
  } catch {
    console.warn(`[ai] Failed to parse build-fix response: ${text.slice(0, 200)}`);
    parsed = { fixes: {} };
  }

  const fixes = new Map<string, string>();
  if (parsed.fixes) {
    for (const [filePath, rawContent] of Object.entries(parsed.fixes)) {
      // Reject model-chosen paths that try to escape the workspace.
      if (!isSafeRelativePath(filePath)) {
        console.warn(`[ai] Rejected unsafe fix path from model: ${filePath}`);
        continue;
      }
      let content = stripMarkdownFences(rawContent);
      // Reject responses that are clearly commentary, not code
      if (
        content.startsWith("// NOTE:") ||
        content.startsWith("// This file could not") ||
        content.startsWith("// Please provide") ||
        content.includes("could not be fully reconstructed")
      ) {
        continue;
      }
      fixes.set(filePath, content);
    }
  }

  return {
    fixes,
    inputTokens: response.usage.input_tokens,
    outputTokens: response.usage.output_tokens,
  };
}

export async function generateSupabaseSchema(
  sourceFiles: Map<string, string>,
  platform: DetectedPlatform,
): Promise<AIResponse> {
  const anthropic = getClient();

  const fileList = Array.from(sourceFiles.entries())
    .map(([path, content]) => `### ${path}\n\`\`\`\n${content.substring(0, 6000)}\n\`\`\``)
    .join("\n\n");

  const response = await anthropic.messages.create({
    model: MODEL,
    max_tokens: 16000,
    system: "You are a database schema migration expert. You output only valid SQL that can be run directly in a Supabase SQL editor. Never wrap output in markdown code fences.",
    messages: [
      {
        role: "user",
        content: `Analyze the following source code from a "${platform}" application and generate a complete Supabase SQL migration file.

## Source Files (containing database operations)
${fileList}

## Instructions
1. Infer ALL database tables, columns, types, and relationships from the source code
2. Generate CREATE TABLE statements with proper PostgreSQL types
3. Add foreign key constraints where relationships are detected
4. Create indexes for columns used in queries/filters
5. Generate Row Level Security (RLS) policies based on detected auth patterns
6. Include ENABLE ROW LEVEL SECURITY for each table
7. Add helpful comments describing each table's purpose

## Output Format
Output a single SQL migration file. Start with:
-- Supabase SQL Migration
-- Generated from ${platform} source code
-- Tables, RLS policies, and indexes

Then the SQL statements in order: extensions, tables, indexes, RLS policies.

CRITICAL: Output raw SQL only. No markdown fences. No explanations before or after the SQL.`,
      },
    ],
  });

  const text =
    response.content[0].type === "text" ? response.content[0].text : "";

  return {
    content: stripMarkdownFences(text).trim(),
    inputTokens: response.usage.input_tokens,
    outputTokens: response.usage.output_tokens,
  };
}

// Fixed input overhead per migrateFile call: system prompt + the migration
// rules/instructions block that is prepended to every file (not part of the
// file content itself). Without this the estimate undercounts input tokens.
const MIGRATE_PROMPT_OVERHEAD_TOKENS = 400;
// Migrated files tend to grow (added Supabase client/boilerplate), so output
// runs larger than the source file rather than ~1.2x.
const OUTPUT_TO_INPUT_RATIO = 1.4;

export function estimateTokens(content: string): {
  input: number;
  output: number;
} {
  const charCount = content.length;
  const fileInputTokens = Math.ceil(charCount / 3.5);
  const estimatedInputTokens = fileInputTokens + MIGRATE_PROMPT_OVERHEAD_TOKENS;
  const estimatedOutputTokens = Math.ceil(fileInputTokens * OUTPUT_TO_INPUT_RATIO);
  return { input: estimatedInputTokens, output: estimatedOutputTokens };
}

const BASE_FEE_CENTS = parseInt(process.env.BASE_FEE_CENTS || "3500"); // $35 per migration (includes database schema generation)

export function calculateCost(
  inputTokens: number,
  outputTokens: number,
): {
  rawCostCents: number;
  tokenCostCents: number;
  baseFeeCents: number;
  billedCostCents: number;
  markup: number;
} {
  const pricing = ANTHROPIC_PRICING[MODEL];
  const markup = parseFloat(process.env.TOKEN_MARKUP_MULTIPLIER || "4");
  const rawCostCents = Math.ceil(
    (inputTokens / 1_000_000) * pricing.input +
      (outputTokens / 1_000_000) * pricing.output,
  );
  const tokenCostCents = Math.ceil(rawCostCents * markup);
  const billedCostCents = tokenCostCents + BASE_FEE_CENTS;

  return { rawCostCents, tokenCostCents, baseFeeCents: BASE_FEE_CENTS, billedCostCents, markup };
}
